In [1]:
!pwd
%matplotlib inline
%reload_ext autoreload
%autoreload 2
import sys
sys.executable

/c/Users/81908/jupyter_notebook/tf_2_work/stock_work/signal_model/notebook


'C:\\Users\\81908\\Anaconda3\\envs\\tfgpu\\python.exe'

# 株価の信号データ作成
- https://www.youtube.com/watch?v=22Eq_0qADf4

In [12]:
import sys
sys.path.append(r'C:\Users\81908\jupyter_notebook\tf_2_work\stock_work\signal_model\code')
import make_signal_all

import datetime

code = 1301#7974#2914

start_date = '2000-01-01'
d_start_date = datetime.datetime.strptime(start_date, '%Y-%m-%d').date()

d_end_date = d_start_date + datetime.timedelta(weeks=4 * 4 + 2)  # 4ヶ月半後までデータとる
print(d_start_date, d_end_date)

output_dir = r'D:\work\signal_model\output\tmp'
is_ticks = True
figsize = (10, 10)
    
df, label, df_last_date, arr = make_signal_all.make_signal(code, d_start_date, d_end_date)
print(label)
display(df)
display(df_last_date)

print(df_last_date.iloc[0])
print(df_last_date.iloc[-1])

print(arr.shape)
print(arr[:3])

2000-01-01 2000-05-06
2


date     close      25MA      75MA
date                                               
2000-01-05 2000-01-05  0.515038  0.499729  0.497552
2000-01-06 2000-01-06  0.500000  0.498374  0.497728
2000-01-07 2000-01-07  0.514815  0.497828  0.498178
2000-01-11 2000-01-11  0.485401  0.497279  0.498814
2000-01-12 2000-01-12  0.514815  0.496999  0.498904
...               ...       ...       ...       ...
2000-04-24 2000-04-24  0.638211  0.497055  0.500459
2000-04-25 2000-04-25  0.478571  0.497583  0.500183
2000-04-26 2000-04-26  0.478102  0.494616  0.499725
2000-04-27 2000-04-27  0.507463  0.496752  0.500000
2000-04-28 2000-04-28  0.462963  0.493484  0.499358

[80 rows x 4 columns]

date   close
0  2000-05-02  1350.0
1  2000-05-08  1380.0
2  2000-05-09  1440.0
3  2000-05-10  1470.0
4  2000-05-11  1450.0
5  2000-05-12  1420.0
6  2000-05-15  1450.0
7  2000-05-16  1430.0
8  2000-05-17  1420.0

date     2000-05-02
close          1350
Name: 0, dtype: object
date     2000-05-17
close          1420
Name: 8, dtype: object
(1, 80, 3)
[[[0.51503759 0.499729   0.49755191]
  [0.5        0.49837354 0.49772769]
  [0.51481481 0.49782786 0.49817801]
  [0.48540146 0.49727891 0.49881354]
  [0.51481481 0.49699864 0.49890351]
  [0.51459854 0.49616858 0.49908525]
  [0.51438849 0.49505495 0.49862663]
  [0.63475177 0.50110436 0.50100853]
  [0.45       0.49751793 0.50036637]
  [0.5        0.49640586 0.50045779]
  [0.57236842 0.49944506 0.50128123]
  [0.43865031 0.49833426 0.5002742 ]
  [0.46078431 0.49721913 0.4996345 ]
  [0.47959184 0.49804796 0.49963437]
  [0.49305556 0.49776474 0.49963424]
  [0.5        0.49943993 0.49954263]
  [0.47902098 0.49719809 0.49926787]
  [0.52857143 0.50224782 0.49880941]
  [0.47916667 0.50084104 0.49853292]
  [0.4929078  0.49887955 0.49843893]
  [0.5        0.49859787 0.49898832]
  [0.48571429 0.50028082 0.49889523]
  [0.52173913 0.50168445 0.49898618]
  [0.5425531

In [3]:
import numpy as np
arr_app = np.append(arr, arr, axis=0)
print(arr_app.shape)
#arr_app = arr_app.transpose(1, 0, 2)
#print(arr_app.shape)

(2, 80, 3)


In [12]:
import numpy as np
a = np.zeros((0, 80, 3))
arr_app = np.append(a, arr, axis=0)
print(arr_app.shape)
arr_app

(1, 80, 3)


array([[[0.50189036, 0.49587449, 0.49836994],
        [0.51006289, 0.49673465, 0.49816914],
        [0.49003736, 0.49779967, 0.49770524],
        [0.53773585, 0.49987749, 0.49898926],
        [0.56969697, 0.50235248, 0.499761  ],
        [0.5470255 , 0.50550068, 0.49942626],
        [0.43614719, 0.50206667, 0.49900336],
        [0.52890173, 0.50388218, 0.49984038],
        [0.4752809 , 0.50280369, 0.50068648],
        [0.4890553 , 0.50149434, 0.50059029],
        [0.49242865, 0.50012033, 0.50027105],
        [0.49941315, 0.49971124, 0.50038256],
        [0.51115678, 0.50132387, 0.50020714],
        [0.52497096, 0.50240385, 0.5005974 ],
        [0.51983003, 0.50390887, 0.5013533 ],
        [0.52222222, 0.50429974, 0.50128787],
        [0.55978261, 0.50756368, 0.50214369],
        [0.51589744, 0.50904134, 0.50242432],
        [0.48939929, 0.50877316, 0.50237104],
        [0.57653061, 0.51205965, 0.50357968],
        [0.54028436, 0.51432205, 0.50428186],
        [0.59111617, 0.51902223, 0

In [22]:
import numpy as np

arr0 = np.load(r'D:\work\signal_model\output\tmp\class_0_arr.npy')
arr1 = np.load(r'D:\work\signal_model\output\tmp\class_1_arr.npy')
arr2 = np.load(r'D:\work\signal_model\output\tmp\class_2_arr.npy')

print(arr0.shape)
print(arr1.shape)
print(arr2.shape)

(121, 80, 3)
(34, 80, 3)
(31, 80, 3)


In [20]:
119 + 24 + 34

177

In [23]:
arr2[0,:,:]

array([[0.51503759, 0.499729  , 0.49755191],
       [0.5       , 0.49837354, 0.49772769],
       [0.51481481, 0.49782786, 0.49817801],
       [0.48540146, 0.49727891, 0.49881354],
       [0.51481481, 0.49699864, 0.49890351],
       [0.51459854, 0.49616858, 0.49908525],
       [0.51438849, 0.49505495, 0.49862663],
       [0.63475177, 0.50110436, 0.50100853],
       [0.45      , 0.49751793, 0.50036637],
       [0.5       , 0.49640586, 0.50045779],
       [0.57236842, 0.49944506, 0.50128123],
       [0.43865031, 0.49833426, 0.5002742 ],
       [0.46078431, 0.49721913, 0.4996345 ],
       [0.47959184, 0.49804796, 0.49963437],
       [0.49305556, 0.49776474, 0.49963424],
       [0.5       , 0.49943993, 0.49954263],
       [0.47902098, 0.49719809, 0.49926787],
       [0.52857143, 0.50224782, 0.49880941],
       [0.47916667, 0.50084104, 0.49853292],
       [0.4929078 , 0.49887955, 0.49843893],
       [0.5       , 0.49859787, 0.49898832],
       [0.48571429, 0.50028082, 0.49889523],
       [0.

In [8]:
import numpy as np

_dir = r'D:\work\signal_model\output\dataset\time_series\train'

arr0 = np.load(_dir + '/class_0_arr.npy')
arr1 = np.load(_dir + '/class_1_arr.npy')
arr2 = np.load(_dir + '/class_2_arr.npy')

print(arr0.shape)
print(arr1.shape)
print(arr2.shape)

print(arr0.shape[0] + arr1.shape[0] + arr2.shape[0])

(22829, 80, 3)
(22829, 80, 3)
(22829, 80, 3)
68487


In [5]:
import numpy as np

_dir = r'D:\work\signal_model\output\dataset\time_series\validation'

arr0 = np.load(_dir + '/class_0_arr.npy')
arr1 = np.load(_dir + '/class_1_arr.npy')
arr2 = np.load(_dir + '/class_2_arr.npy')

print(arr0.shape)
print(arr1.shape)
print(arr2.shape)

print(arr0.shape[0] + arr1.shape[0] + arr2.shape[0])

(12808, 80, 3)
(3192, 80, 3)
(3314, 80, 3)
19314


In [6]:
import numpy as np

_dir = r'D:\work\signal_model\output\dataset\time_series\test'

arr0 = np.load(_dir + '/class_0_arr.npy')
arr1 = np.load(_dir + '/class_1_arr.npy')
arr2 = np.load(_dir + '/class_2_arr.npy')

print(arr0.shape)
print(arr1.shape)
print(arr2.shape)

print(arr0.shape[0] + arr1.shape[0] + arr2.shape[0])

(12774, 80, 3)
(4509, 80, 3)
(3066, 80, 3)
20349


In [3]:
import numpy as np

_dir = r'D:\work\signal_model\output\dataset\time_series_v2\orig\validation'

arr0 = np.load(_dir + '/class_0_arr.npy')
arr1 = np.load(_dir + '/class_1_arr.npy')
arr2 = np.load(_dir + '/class_2_arr.npy')

print(arr0.shape)
print(arr1.shape)
print(arr2.shape)

print(arr0.shape[0] + arr1.shape[0] + arr2.shape[0])

(3192, 80, 3)
(3192, 80, 3)
(3192, 80, 3)
9576


In [5]:
import tensorflow as tf
import tensorflow.keras.layers as layers
def create_vgg_2d(input_shape=(80, 3), n_class=3, activation="softmax"):
    """2次元データのVGGっぽいの"""
    inputs = layers.Input(input_shape)
    x = inputs
    for ch in [64, 128, 256]:
        x = layers.Conv1D(ch, 3, padding='same')(x)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        if ch != 256:
            x = layers.AveragePooling1D(2)(x)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dense(n_class, activation=activation)(x)
    return tf.keras.models.Model(inputs, x)

model = create_vgg_2d()
model.summary()

model.predict(arr_app)

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 80, 3)]           0         
_________________________________________________________________
conv1d (Conv1D)              (None, 80, 64)            640       
_________________________________________________________________
batch_normalization (BatchNo (None, 80, 64)            256       
_________________________________________________________________
re_lu (ReLU)                 (None, 80, 64)            0         
_________________________________________________________________
average_pooling1d (AveragePo (None, 40, 64)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 40, 128)           24704     
_________________________________________________________________
batch_normalization_1 (Batch (None, 40, 128)           512   

array([[0.3303744 , 0.32830533, 0.34132022],
       [0.3303744 , 0.32830533, 0.34132022]], dtype=float32)

In [7]:
import tensorflow as tf
import tensorflow.keras.layers as layers

def create_resnet_2d(input_shape=(80, 3), n_class=3, activation="softmax"):
    """2次元データのresnet"""
    def residual_block(inputs, ch, strides):
        # main path
        x = layers.BatchNormalization()(inputs)
        x = layers.ReLU()(x)
        x = layers.Conv1D(ch, 3, strides=strides, padding="same",
                          kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        x = layers.Conv1D(ch, 3, padding="same",
                          kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
        # shortcut path
        if inputs.shape[-1] != ch or strides > 1:
            s = layers.Conv1D(ch, 3, strides=strides, padding="same",
                          kernel_regularizer=tf.keras.regularizers.l2(1e-4))(inputs)
        else:
            s = inputs
        # add
        x = layers.Add()([x, s])
        return x

    def main():
        inputs = layers.Input(input_shape)
        x = layers.Conv1D(16, 3, padding="same")(inputs)
        for ch in [16, 32, 64]:
            for i in range(7):
                strides = 2 if i == 0 else 1
                if ch == 16:
                    strides = 1
                x = residual_block(x, ch, strides)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        x = layers.GlobalAveragePooling1D()(x)
        x = layers.Dense(n_class, activation=activation)(x)

        return tf.keras.models.Model(inputs, x)
    
    return main()

model = create_resnet_2d(input_shape=(80, 3), n_class=3)
model.summary()

model.predict(arr_app)

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 80, 3)]      0                                            
__________________________________________________________________________________________________
conv1d_48 (Conv1D)              (None, 80, 16)       160         input_3[0][0]                    
__________________________________________________________________________________________________
batch_normalization_46 (BatchNo (None, 80, 16)       64          conv1d_48[0][0]                  
__________________________________________________________________________________________________
re_lu_46 (ReLU)                 (None, 80, 16)       0           batch_normalization_46[0][0]     
____________________________________________________________________________________________

array([[0.39644468, 0.48411214, 0.11944313],
       [0.39644468, 0.48411214, 0.11944313]], dtype=float32)

In [4]:
import os
import numpy as np

orig_npy_dir = r'C:\Users\81908\jupyter_notebook\tf_2_work\stock_work\signal_model\output\orig_date_all'
classes = ['0', '1', '2']
class_arrs = [np.load(os.path.join(orig_npy_dir, f'class_{c}_arr.npy')) for c in classes]
len_arrs = [class_arr.shape[0] for class_arr in class_arrs]
len_arrs

[86411, 21672, 28125]

In [5]:
class_arrs[0].shape

(86411, 80, 3)

In [10]:
class_arrs[0][0,:,:]

array([[0.54347826, 0.50027685, 0.49926335],
       [0.52083333, 0.50055356, 0.49953926],
       [0.48639456, 0.49861687, 0.49834055],
       [0.47931034, 0.49778393, 0.49898421],
       [0.52112676, 0.49805664, 0.49981512],
       [0.4862069 , 0.49666203, 0.49990754],
       [0.49300699, 0.49692995, 0.49990754],
       [0.53521127, 0.49832027, 0.50036989],
       [0.46598639, 0.49719574, 0.50018488],
       [0.53521127, 0.49775028, 0.50027726],
       [0.5       , 0.49689966, 0.50055437],
       [0.47959184, 0.49604184, 0.50036938],
       [0.51388889, 0.49829691, 0.50055386],
       [0.47260274, 0.49943133, 0.50036904],
       [0.52816901, 0.49914651, 0.50046113],
       [0.47260274, 0.50113895, 0.49953909],
       [0.48591549, 0.50483504, 0.4996311 ],
       [0.53571429, 0.50141523, 0.50027678],
       [0.4862069 , 0.50169587, 0.49990777],
       [0.49300699, 0.50225734, 0.49953879],
       [0.49295775, 0.50168919, 0.49889258],
       [0.5212766 , 0.50393479, 0.50009239],
       [0.

In [16]:
import os
import numpy as np

X_test, y_test = None, None
for cla in ['0', '1', '2']:
    X = np.load(os.path.join(r'D:\work\signal_model\output\dataset\all', f'class_{cla}_test.npy'))
    y = np.array([cla] * X.shape[0])
    if X_test is None and y_test is None:
        X_test = X
        y_test = y
    else:
        X_test = np.append(X_test, X, axis=0)
        y_test = np.append(y_test, y, axis=0)

def label2onehot(labels: np.ndarray):
    """
    sklearnでnp.ndarrayのラベルをonehot化
    Args:
        labels:onehot化するラベル名の配列.np.array(['high' 'high' 'low' 'low'])のようなの
    Returns:
        enc:ラベル名を0-nの連番にした配列。np.array([[0] [0] [1] [1]])のようなの
        onehot:ラベル名をonehotにした配列。np.array([[1. 0.] [1. 0.] [0. 1.] [0. 1.]])のようなの
    Usage:
        labels = df['aaa'].values
        enc, onehot = label2onehot(labels)
    """
    from sklearn import preprocessing
    from sklearn.preprocessing import OneHotEncoder

    enc = preprocessing.LabelEncoder().fit_transform(labels).reshape(-1,1)
    onehot = OneHotEncoder().fit_transform(enc).toarray()
    return enc, onehot

_, y_test = label2onehot(y_test)

In [15]:
print(X_test.shape, y_test.shape)
y_test

(3291, 80, 3) (3291, 3)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])